### ISSUE TITLE
Scrolling problem.

### ISSUE THREAD

**Issue by MMortaga** [facg3/SSST#16]
The navigation bar works pretty well and I am able to navigate through the webpage easily. However, the scroll bar seems to be broken.
What I personally did to fix this is go through the code, and change `<scroll-page>` to `<div>` in addition to getting rid of the scroll-container.
![Screenie](https://i.imgur.com/TxZcif7.png)

**Comment by sultanassi95** [comment]
Can you please check the new code? if there  is still an issue, can you update us?
