### ISSUE TITLE
Miss used elements

### ISSUE THREAD

**Issue by NouraldinS** [facg3/SSST#19]
Elements like <ul> or <ol> expect to have <li> elements inline. But if you wouldn't do that you could just use divs or sections depending on the function you're making.

![image](https://user-images.githubusercontent.com/28482442/32591969-525b61fe-c52a-11e7-86ec-75cda3a54444.png)

**Comment by sultanassi95** [comment]
Can you please check the new code? if there  is still an issue, can you update us?
