### ISSUE TITLE
Styling on selectors other than classes.

### ISSUE THREAD

**Issue by ZooeyMiller** [facg3/SSST#22]
I raised the same issue on another team's project so will link to it here: 
https://github.com/facg3/birdies/issues/20

**Comment by sultanassi95** [comment]
Can you please check the new code? if there  is still an issue, can you update us?

**Comment by ZooeyMiller** [comment]
I've had a look and you are still styling on IDs in places (such as [line 41 of your css](https://github.com/facg3/SSST/blob/master/style.css#L41)) so this isn't quite ready to be close yet. 

It's not the end of the world to do this, and the refactor on this project isn't the most important this, but moreso for your next projects I would recommend just using classes for styling (rather than IDs and directly styling HTML elements)

**Comment by sultanassi95** [comment]
Noted Zooey :+1: 
we will get to their :100: 
it was a great week, good to have u guys.
@ZooeyMiller @yvonne-liu
