### ISSUE TITLE
Form elements arrangement 

### ISSUE THREAD

**Issue by aajour** [facg3/SSST#25]
From the best practice rules when using HTML forms, is to have label/input pairs wrapped with a block level element (e.g. <p>)

Also using `For` attribute is from best practice rules, and you using it well :thumbsup:
![bitmoji](https://render.bitstrips.com/v2/cpanel/43533bc8-de9f-4e89-9f7d-f9a64b6254c4-9ac89064-01d0-469c-9651-d36e34d91224-v1.png?transparent=1&palette=1&width=246)

**Comment by sultanassi95** [comment]
Can you please check the new code? if there  is still an issue, can you update us?
